Repository gazprom-neft/SeismicPro, pull requests merged in 2023-05, with the labels that each got.

#138 Hotfix for gather getitem
  seismicpro/gather/gather.py
Labels: bug

#133 Speed up cube stacking
  seismicpro/__init__.py
  seismicpro/batch.py
  seismicpro/config.py
  seismicpro/dataset.py
  seismicpro/gather/gather.py
  seismicpro/survey/survey.py
Labels: enhancement

#136 Refactor velocity model
  README.md
  seismicpro/gather/gather.py
  seismicpro/stacking_velocity/__init__.py
  seismicpro/stacking_velocity/stacking_velocity.py
  seismicpro/stacking_velocity/velocity_model.py
  seismicpro/velocity_spectrum/velocity_spectrum.py
  setup.py
Labels: enhancement

#142 Allow passing sample_interval and delay upon Survey construction
  seismicpro/survey/survey.py
  setup.py
Labels: enhancement

#143 Now Gather.__getitem__ works with array indexers
  seismicpro/gather/gather.py
  seismicpro/tests/test_gather.py
Labels: bug

#140 Refactor stretch muting during NMO correction
  README.md
  seismicpro/gather/gather.py
  seismicpro/gather/utils/correction.py
  seismicpro/velocity_spectrum/velocity_spectrum.py
Labels: bug, enhancement

#141 Plot velocity bounds on top of spectrums
  seismicpro/velocity_spectrum/interactive_plot.py
  seismicpro/velocity_spectrum/velocity_spectrum.py
Labels: enhancement

#134 add load and dump headers
  seismicpro/containers.py
  seismicpro/gather/gather.py
  seismicpro/gather/metrics.py
  seismicpro/refractor_velocity/refractor_velocity_field.py
  seismicpro/survey/survey.py
  seismicpro/tests/test_dump_load_headers.py
  seismicpro/tests/test_gather.py
  seismicpro/utils/file_utils.py
  seismicpro/utils/general_utils.py
  setup.py
Labels: enhancement
